### 모듈(라이브러리)
 - 확장자가 .py인 파일
 - 변수나 함수 또는 클래스를 모아놓은 파일.
 - 파이썬 프로그램에서 불러와 사용할 수 있게끔 만들어진 파이썬 파일이라고 한다
 
 - Numpy -> 고성능 과학계산을 위한 데이터 분석 라이브러리
 - Pandas -> 형과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리
 - Matplotlib -> 2D 그래프로 시각화가 가능한 라이브러리

NumPy의 주요 기능
- 빠르고 효율적인 벡터 산술연산을 제공하는 다차원배열 제공 (ndarray 클래스)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수
- 선형대수, 난수 생성, 푸리에 변환

In [1]:
# numpy 라이브러리 import 하기
# 앞으로 np라는 이름으로 부르기
import numpy as np

numpy.ndarray 클래스
- 동일한 자료형을 가지는 값들이 배열 형태로 존재함

In [2]:
# array 생성하기
list1 = [1,2,3,4,5]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
# 연산을 진행하면 각 요소끼리 연산을 진행
arr + arr1

array([ 2,  4,  6,  8, 10])

In [5]:
arr * arr1

array([ 1,  4,  9, 16, 25])

In [6]:
# 리스트
# [1,2,3] , [4,5,6] 각 요소의 값을 더한다

In [7]:
list1 = [1,2,3]
list2 = [4,5,6]

In [8]:
list3 = []
for i in range(3):
    list3.append(list1[i] + list2[i])
list3

[5, 7, 9]

In [9]:
# 2차원 array 생성하기
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# array의 크기 확인하기
# shape
arr2.shape

(2, 3)

In [11]:
# array의 전체 요소 개수 확인하기
# size
arr2.size

6

In [12]:
# array의 타입 확인하기
# dtype
arr2.dtype

dtype('int32')

In [13]:
# array의 차원 확인하기
# ndim
arr2.ndim

2

In [14]:
# 3차원의 array 만들고 배열의 크기, 차원, 전체 요소개수 확인
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
print('배열의 크기 : {}'.format(arr3.shape))
print(f'배열의 차원 : {arr3.ndim}')
print('배열의 개수 :',arr3.size)

배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 개수 : 8


In [16]:
# 배열 생성하기
# 0값으로 생성하기
# zeros(배열의 크기)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# 1값으로 생성하기
# ones()
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# 지정해서 생성하기
# full(배열의 크기, 채워넣을 값)
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
# 연속되는 숫자로 배열 생성하기
# arange(시작하는 수, 끝나는 수+1, 간격이 되는 수)
# 시작하는 수 기본값 : 0
# 간격이 되는 수 기본값 : 1
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
np.arange(1,50,10)

array([ 1, 11, 21, 31, 41])

In [23]:
# 1부터 50까지 1씩 커지는 배열 만들기
# np.linspace(시작하는 수, 끝내는 수, 등분할 값)
# 같은 간격만큼의 배열을 만들 때 사용
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [24]:
for i in np.linspace(1,50,20):
    print(i)

1.0
3.5789473684210527
6.157894736842105
8.736842105263158
11.31578947368421
13.894736842105264
16.473684210526315
19.05263157894737
21.63157894736842
24.210526315789473
26.789473684210527
29.36842105263158
31.94736842105263
34.526315789473685
37.10526315789474
39.68421052631579
42.26315789473684
44.8421052631579
47.421052631578945
50.0


In [69]:
# 랜덤값으로 배열 생성하기
# np.random.rand(배열의 크기)
# 0 ~ 1 사이의 값을 가지는 배열을 생성
소숫점 = np.random.rand(2,3)
소숫점

array([[0.57048937, 0.81997519, 0.987647  ],
       [0.26180845, 0.67373946, 0.89810577]])

In [71]:
# 원하는 범위에서 랜덤값 생성
# np.random.randint(시작수, 끝수+1, size = 배열의 크기)
정수 = np.random.randint(2,10,size = (3,2))
정수

array([[3, 8],
       [5, 2],
       [6, 2]])

In [74]:
# 2부터 10까지의 랜덤한 실수값으로 이루어진 (5,4) 크기의 배열 생성
실수 = np.random.randint(2,10, size = (5,4)) + np.random.rand(5,4)
실수

array([[8.8820534 , 7.03555729, 4.78635839, 6.52653826],
       [9.58935617, 7.31408503, 2.47406411, 5.97039164],
       [7.2874157 , 3.02057335, 3.50495247, 6.97744744],
       [5.62005897, 3.58267408, 6.59457886, 5.06658699],
       [7.14867457, 6.31426396, 7.74123286, 5.63452797]])

In [66]:
# 5부터 6까지 랜덤한 실수
5 + np.random.rand(2,3)

array([[5.80575799, 5.59243221, 5.27379631],
       [5.24839724, 5.19669325, 5.26610166]])

In [ ]:
# 타입 변경하기
# 배열.astype("변경할 타입")

In [78]:
실수.astype("int")

array([[8, 7, 4, 6],
       [9, 7, 2, 5],
       [7, 3, 3, 6],
       [5, 3, 6, 5],
       [7, 6, 7, 5]])

In [ ]:
### 배열의 생성 ###

In [ ]:
### 배열의 기능 ###

In [79]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
# 인덱싱
# []
# 2차원에서 0번째 출력
arr[0]

array([1, 2, 3])

In [83]:
arr[0][1]

2

In [84]:
arr[0,1]

2

In [ ]:
# 슬라이싱

In [87]:
# 0 ~ 9 까지의 값이 담긴 배열 생성
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
# 3부터 7까지의 값 출력
arr1[3:8]

array([3, 4, 5, 6, 7])

In [93]:
# 0 ~ 49 까지 정수의 값이 담겨있는 array 생성하기
arr2 = np.arange(50)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [98]:
# arr2를 (5,10)으로 재 배열하기
# reshape
# 바뀌기 전과 후의 데이터 수가 똑같아야함
arr2 = arr2.reshape(5,10) # 출력을 진행하고 저장은 진행되지 않음, 변수에 담아주어야 저장이 됨

In [99]:
# 2차원 슬라이싱
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [102]:
# 시작수 : 끝수 +1
# : 끝수 +1 = 처음부터 끝수까지
# 시작수 : = 시작수부터 끝까지
# : = 처음부터 끝까지
arr2[0:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [105]:
arr2[:, : 1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [108]:
arr2[0:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [110]:
# 파일 불러오기
data = np.loadtxt("height_weight.txt", delimiter = ',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [116]:
result =  data[1:,:] / (data[:1,:] * data[:1,:]) * 10000
result

array([[21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
        20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998]])

In [117]:
# data에서 키와 몸무게 분리하기
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [121]:
키_cm = data[0]
키_cm

array([175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
       179. ])

In [122]:
키_m = 키_cm / 100
키_m

array([1.752, 1.803, 1.75 , 1.692, 1.852, 1.88 , 1.776, 1.782, 1.77 ,
       1.79 ])

In [119]:
몸무게 = data[1]
몸무게

array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ])

In [123]:
몸무게 / (키_m * 키_m)

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [124]:
# Boolean 인덱싱
# True는 출력하고 False는 출력하지 않음
# 인덱싱을 진행할 때 값의 개수와 동일한 수의 불리언 데이터 필요
# 원하는 조건에 맞는 값을 출력하는 방법
arr3 = np.array([10,20,15,30])
arr3

array([10, 20, 15, 30])

In [125]:
bol = np.array([True,False,True,False])
bol

array([ True, False,  True, False])

In [126]:
arr3[bol]

array([10, 15])

In [ ]:
# 17 미만인 값 출력
arr3[arr3 < 17]

In [130]:
# arr3에서 20인 값만 출력
print(arr3 == 20)
arr3[arr3 == 20]

[False  True False False]


array([20])

In [ ]:
# numpy에서 사용하는 연산 함수

In [133]:
# 1 ~ 9 까지의 랜덤한 정수가 담긴 2,5 크기의 배열 생성
arr = np.random.randint(1,10,size=(2,5))
arr

array([[7, 7, 7, 5, 5],
       [4, 4, 8, 1, 2]])

In [135]:
# 배열 안에 있는 값 합계 
# np.sum(배열값)
np.sum(arr, axis = 0)

array([11, 11, 15,  6,  7])

In [136]:
np.sum(arr, axis = 1)

array([31, 19])

In [137]:
# 배열 안에 있는 값의 평균
# np.mean(배열값)
np.mean(arr, axis = 0)

array([5.5, 5.5, 7.5, 3. , 3.5])

In [140]:
np.mean(arr)

5.0

In [138]:
np.mean(arr, axis = 1)

array([6.2, 3.8])

### 영화 평점 데이터 분석하기

In [167]:
# 데이터 타입 변경
# dtype
data = np.loadtxt('ratings.txt', delimiter = "::",dtype='int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [160]:
# 전체 평점 평균 구하기
np.mean(data[ : , 2])


3.581564453029317

In [175]:
# 각 사용자별 평점 평균 구하기
# 리스트에 [사용자, 사용자의 평점평균]
# 1번 사용자 평점 평균 구하기 > 1 ~ 6040
user_list = []
# data[:,0] 전체 정보에서 id 값만 출력
user = data[data[:,0]==1] # 전체 정보에서 id값이 1인 값만 출력
# 출력된 값(user)에서 평점값만 추출한 후 평균 구하기
user_list.append([1, np.mean(user[ : ,2]) ]) # 1번 사용자에 대한 평점 평균
user_list

i = 1
while i<6040:
    user = data[data[:,0]==i]
    user_list.append([i, np.mean(user[ : ,2])])
    i+=1
user_list

[[1, 4.188679245283019],
 [1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.

In [180]:
user_list = []
for i in range(1,6041): # 1 ~ 6040까지 반복되는 반복문
    user = data[data[:,0]==i] # 반복될 때마다 다른 유저(1 ~ 6040)의 정보를 출력
    user_list.append([i, np.mean(user[ : ,2]) ])
user_list

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [178]:
# 각 사용자별 평균 평점이 4점 이상인 사용자 구하기
user_list = []
for i in range(1,6041):
    user = data[data[:,0]==i]
    if np.mean(user[:,2]) >=4:
        user_list.append(i)
user_list

[1,
 4,
 7,
 10,
 17,
 20,
 27,
 36,
 43,
 46,
 53,
 54,
 55,
 64,
 65,
 67,
 69,
 74,
 75,
 76,
 81,
 82,
 86,
 88,
 91,
 97,
 101,
 103,
 105,
 106,
 109,
 112,
 121,
 124,
 125,
 126,
 128,
 129,
 130,
 138,
 150,
 152,
 153,
 156,
 158,
 161,
 162,
 164,
 171,
 177,
 183,
 184,
 186,
 187,
 189,
 196,
 205,
 210,
 213,
 215,
 220,
 222,
 228,
 230,
 231,
 233,
 234,
 235,
 239,
 244,
 246,
 248,
 252,
 255,
 257,
 259,
 265,
 266,
 270,
 274,
 275,
 283,
 285,
 288,
 291,
 297,
 299,
 300,
 307,
 309,
 311,
 313,
 316,
 320,
 322,
 325,
 330,
 332,
 336,
 339,
 341,
 343,
 345,
 346,
 356,
 366,
 367,
 372,
 374,
 375,
 376,
 379,
 381,
 382,
 399,
 404,
 408,
 412,
 413,
 417,
 420,
 421,
 427,
 434,
 437,
 444,
 446,
 447,
 450,
 451,
 452,
 455,
 466,
 469,
 472,
 473,
 485,
 486,
 494,
 496,
 502,
 503,
 505,
 514,
 518,
 521,
 523,
 525,
 527,
 529,
 530,
 537,
 538,
 543,
 553,
 564,
 567,
 568,
 574,
 577,
 582,
 583,
 584,
 586,
 588,
 589,
 590,
 592,
 594,
 597,
 605,
 60

In [181]:
# 각 사용자별 평균 평점이 4점 이상인 사용자 구하기
user_np = np.array(user_list)
user_np

array([[1.00000000e+00, 4.18867925e+00],
       [2.00000000e+00, 3.71317829e+00],
       [3.00000000e+00, 3.90196078e+00],
       ...,
       [6.03800000e+03, 3.80000000e+00],
       [6.03900000e+03, 3.87804878e+00],
       [6.04000000e+03, 3.57771261e+00]])

In [184]:
over4bol = user_np[:,1] >= 4

In [187]:
user_np[over4bol,0].astype('int') # 평균 평점이 4점 이상인 사용자의 모든 정보

array([   1,    4,    7, ..., 6027, 6032, 6034])